site_name: Luminosity
site_url: https://AvePhysica.github.io/notes/
repo_url: https://github.com/AvePhysica/notes
repo_name: Github

nav:
  - 首页: index.md
  - About me: about.md
  - 笔记:
      - Quantum Field Theory: 
          - Coleman QFT - Lecture 1. 在量子力学中引入相对论: notes/Coleman QFT - Lecture 1. 在量子力学中引入相对论.md
  - 代码:
      - README: code/README.md

theme:
  name: material
  language: zh

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
